var tree_node=new Array(0,"Process Lot","","","","",4,"","","",-1,2,"by Equipment","by Equipment","","",3,"","#","",2,"by recipe","by recipe","","",3,"","","",2,"by Lot","by Lot","","",3,"","","",1,0,"Schedule and Start","","","","",4,"","","",-1,2,"Schedule Lot","","","",3,"","./lschedule_lot.htm","mainFrame",2,"Start Lot","","","",3,"","./new_lot_start.htm","mainFrame",2,"Cancel Sched Lot","","","",3,"","./cancel_scheduled_lot.htm","mainFrame",1,2,"Data Collecion","Data Collecion","","",4,"","","",2,"ON/OFF","ON/OFF","","",4,"","","",0,"Lot Change","","","","",4,"","","",-1,2,"Lot Change","Change Lot in One GUI","","",3,"","./change_lotinfo.htm","mainFrame",2,"Change Lot ID","Change Lot ID","","",3,"","./change_lotid.htm","mainFrame",2,"Change Priority","Change Lot Priority","","",3,"","./change_lotprior.htm","mainFrame",2,"Change Type","Change Lot Type","","",3,"","./change_lottype.htm","mainFrame",2,"ReId Components","Reidentify Components","","",3,"","./change_reidentify.htm","mainFrame",2,"Secnd RejectCode","Second Reject Code","","",3,"","./change_secondrejectcode.htm","mainFrame",2,"Change Comments","Change Comments","","",3,"","./change_startcomment.htm","mainFrame",1,0,"Lot Comment","","","","",4,"","","",-1,2,"Add Comments","Add Comments","","",3,"","./add_comment.htm","mainFrame",2,"Change Comments","Change Comments","","",3,"","./change_startcomment.htm","mainFrame",1,0,"Special Function","Special Function","","","",4,"","","",-1,2,"Abort Step","Abort Step","","",3,"","./abort_step.htm","mainFrame",2,"Skip Step","Skip Step","","",3,"","./skip_step.htm","mainFrame",2,"Back Up","Back Up a Lot","","",3,"","./backup_step.htm","mainFrame",2,"Reroute Lot","Reroute Lot","","",3,"","./reroute_lot.htm","mainFrame",1,0,"Hold/Rel Function","Hold/Release Function","","","",4,"","","",-1,2,"Immediate Hold","","","",3,"","./immediate_hold.htm","mainFrame",2,"Release Hold","Release Hold","","",3,"","./release_hold.htm","mainFrame",2,"Remove FutuHold","Remove Future Hold","","",3,"","./cancel_lot_futureHold.htm","mainFrame",2,"Sche FutuHold","Schedule Future Hold","","",3,"","./schedule_lot_futureHold.htm","mainFrame",1,0,"View","View","","","",4,"","","",-1,2,"Lot View","Lot View","","",3,"","view_lot.htm","mainFrame",2,"Lot History View","Lot History View","","",3,"","","",1,2,"Promis Native","","","",4,"","","",2,"Recipe Search","","","",3,"","./recipe_search.htm","mainFrame",5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{font-family:Verdana;font-size:10pt;font-weight:bold;color:#EA7E13;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{font-family:Verdana;font-size:10pt;font-weight:bold;background-color:#FAFAFA;color:#EA7E13;border:1pt solid #828282;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{font-family:Verdana;font-size:10pt;font-weight:bold;background-color:#FAFAFA;color:#EA7E13;border:1pt solid #5D5D5D;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{font-family:Verdana;font-size:10pt;font-weight:bold;color:#3772DD;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{font-family:Verdana;text-decoration:underline;font-size:10pt;font-weight:bold;color:#3772DD;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{font-family:Verdana;font-size:10pt;font-weight:bold;background-color:#FAFAFA;color:#3772DD;border:1pt solid #5D5D5D;height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=true;
tree.Indent=13;
tree.folderImg1="treeimg/clsfld.gif";
tree.lineFolder="treeimg/";
tree.folderImg2="treeimg/openfld.gif";
tree.fileImg="treeimg/link.gif";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
